### PR TITLE
Allow template-haskell 2.9 (GHC 7.8)

### PR DESCRIPTION
**Pull request by bergmark**

### CODE REVIEW

**Comment by dreixel** [comment]
Thanks!

**Comment by bergmark** [comment]
Thank you as well! :)

**Comment by bergmark** [comment]
@dreixel can you upload this to hackage please?

**Comment by dreixel** [comment]
Done: http://hackage.haskell.org/package/regular-0.3.4.3

**Comment by bergmark** [comment]
Thanks again!

**Pull request merged**
